version: '3'
services:
  back:
    image: lauradlz/back-app
    environment:
      - CURRENT_ENVIRONMENT=production
  front:
    image: lauradlz/front-app
    ports:
      - "8080:80"
    environment:
      - WS_BACK_URL=http://localhost:5000